# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e440edd90ae9e722318d503b9f2c6a9b32d7f62caa5acd4a9365d625e4ec6c800cf1b2a096b884750064af99adb236836a338481224c370aa8d8bbe69e0983c

test:
  secret_key_base: d967210875a0187449e49e83f8a35288f983b024f8335b332d81ee9af33c448897c358bbf3b02fed686da25426c48a72280bf8d9e05a927f57d36953e254f8ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
